version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: system-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: system_db
      MYSQL_USER: system_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - system-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: system-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - system-network

volumes:
  mysql_data:

networks:
  system-network:
    driver: bridge